version: "1.1"

services:
  backend:
    build: ./backend
    container_name: resume-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: resume-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/src
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: resume-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewStrongPassword1234
      POSTGRES_DB: resume_ai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
